<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.9.5 on win32)" generated="20210705 19:04:44.169" rpa="false" schemaversion="2">
<suite id="s1" name="Mobile Testing" source="C:\Users\vaaxa\OneDrive\Backup Dropbox\Backup Onedrvive\Documentos\Projetos\Prime Experts\PrimeExperts_junho_28_2021\mobile_testing">
<suite id="s1-s1" name="Mobile Test" source="C:\Users\vaaxa\OneDrive\Backup Dropbox\Backup Onedrvive\Documentos\Projetos\Prime Experts\PrimeExperts_junho_28_2021\mobile_testing\mobile_test.robot">
<kw name="Abrir o aplicativo no celular" library="resource.mobile" type="SETUP">
<kw name="Open Application" library="AppiumLibrary">
<arg>${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<arg>automationName=${AUTOMATION_NAME}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210705 19:05:06.823" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210705 19:05:06.823" endtime="20210705 19:05:06.823"/>
</kw>
<msg timestamp="20210705 19:05:06.823" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210705 19:05:06.839" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20216ms.
</msg>
<status status="FAIL" starttime="20210705 19:04:44.419" endtime="20210705 19:05:06.839"/>
</kw>
<status status="FAIL" starttime="20210705 19:04:44.419" endtime="20210705 19:05:06.839"/>
</kw>
<test id="s1-s1-t1" name=" Caso de Teste 01:Pesquisar canal “Adrenaline”">
<status status="FAIL" starttime="20210705 19:05:06.839" endtime="20210705 19:05:06.839">Parent suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20216ms.
</status>
</test>
<doc>arquivo responsavel pelos testes do mobile testing App: YouTube</doc>
<status status="FAIL" starttime="20210705 19:04:44.185" endtime="20210705 19:05:06.839">Suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20216ms.
</status>
</suite>
<status status="FAIL" starttime="20210705 19:04:44.169" endtime="20210705 19:05:06.839"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Mobile Testing">Mobile Testing</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Mobile Test">Mobile Testing.Mobile Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210705 19:04:44.201" level="ERROR">Error in file 'C:\Users\vaaxa\OneDrive\Backup Dropbox\Backup Onedrvive\Documentos\Projetos\Prime Experts\PrimeExperts_junho_28_2021\mobile_testing\resource.mobile.robot' on line 21: Setting variable 'aylists' failed: Invalid variable name 'aylists'.</msg>
<msg timestamp="20210705 19:05:06.823" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
